threadPool:
  maxPoolSize: 1024
  corePoolSize: 50
  queueCapacity: 20
  keepAliveSeconds: 20
  weitForTasksToCompleteOnShutdown: true

http:
  maxTotal: 100
  retryLimit: 3
  socketTimeout: 10000
  connectTimeout: 1000
  defaultMaxPerRoute: 20
  connectionRequestTimeout: 1500
  staleConnectionCheckEnabled: true
